default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: eternalalchemy
  password: <%= Rails.application.credentials.postgres[:password] || 'eternalalchemy' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eternalalchemy_development

test:
  <<: *default
  database: eternalalchemy_test

production:
  <<: *default
  database: eternalalchemy
