name: Test and Deployment

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker containers
      run: |
        docker-compose build
    - name: Start Docker containers
      run: |
        docker-compose up -d
    - name: Set up database
      run: |
        docker-compose run -e "RAILS_ENV=test" app bundle exec rails db:create db:migrate
    - name: Run tests
      run: |
        docker-compose run -e "RAILS_ENV=test" app bundle exec rspec
    - name: Cleanup Docker containers
      run: |
        docker-compose down
